export const OPEN_NOTICE_BOARD = "OPEN_NOTICE_BOARD"
export const CLOSE_NOTICE_BOARD = "CLOSE_NOTICE_BOARD"
export const CHANGE_NOTICE_BOARD = "CHANGE_NOTICE_BOARD"
export const CHANGE_TITLE_NOTICE_BOARD = "CHANGE_TITLE"
