export const FETCH_API = "FETCH_API"
export const FETCH_API_SUCCESS = "FETCH_API_SUCCESS"
export const FETCH_API_FAILURE = "FETCH_API_FAILURE"

export const FILTER_TASK = "FILTER_TASK"
export const FILTER_TASK_SUCCESS = "FILTER_TASK_SUCCESS"

export const ADD_TASK = "ADD_TASK"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE"

export const UPDATE_TASK = "UPDATE_TASK"
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE"

export const DELETE_TASK = "DELETE_TASK"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE"
